name: somatic-server
services:
  - type: web
    name: somatic-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://somatic-client.vercel.app
      - key: ADMIN_PASSWORD
        sync: false
      - key: PORT
        value: 5000